version: "3"
services: 
  go_app:
    container_name: go_app
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    tty: true
    volumes:
      - ./src/go_app:/go/src
    env_file:
      - ./docker/go/.go_env
    ports:
      - 8000:80
      - 2345:2345
  next_app:
    container_name: next_app
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    volumes:
      - ./src/next_app:/usr/src/app
    ports:
      - 80:3000
    command: sh -c "npm run dev"
  # MariaDB のコンテナ
  go_test_mariadb:
    container_name: go_test_mariadb
    image: mariadb:10.5.4
    environment:
      # ユーザー名やパスワードなどは適宜変更してください
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - ./docker/db/data:/var/lib/mysql
  go_test_phpmyadmin:
    container_name: go_test_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: go_test_mariadb
    depends_on:
      - go_test_mariadb
    ports:
      - 8080:80
    volumes:
      - /sessions